### ISSUE TITLE
Auth: API Key based Auth

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#1005]
Parent Issue: #969 119

Support API Key based Auth (passed in headers/query params)

**Comment by cecilia-gh** [comment]
Any updates on when will API Key based auth will be available?

**Comment by GimpMaster** [comment]
I would love to know the status of this as well. Since you just closed my duplicate ticket saying you will not implement this. Looking at latest bruno I still don't see an API Key

![image](https://github.com/usebruno/bruno/assets/7818200/6ed560a9-689d-4097-a801-aa5100f70ab1)

@sanjai0py  - Is there a different way to use an API key. I see you took time to make a commit. Is this not merged into the master branch yet?

**Comment by GimpMaster** [comment]
@sanjai0py  - Any updates on this issue? I thought I saw a PR that had it in it but it hasn't been merged. I could be wrong.

**Comment by helloanoop** [comment]
TJusr merged the PR for this. This should be available in `v1.30.0` release scheduled to go out next week.
