### ISSUE TITLE
[Bug] JSON Linting do not recognize comments

### ISSUE THREAD

**Issue by pove** [usebruno/bruno#1008]
This new feature #925 adds an error flag when using comments in JSON:

![image](https://github.com/usebruno/bruno/assets/10817653/8ddd8a40-405e-4088-98fd-5bc6fd86fd2f)

**Comment by Oryss** [comment]
JSON does not support comments

**Comment by pove** [comment]
> JSON does not support comments
> 
> https://stackoverflow.com/a/4183018

Correct. But Visual Studio supports comments in JSON, Postman supports them and also Bruno does. However, linting is showing an error here. See my point?

**Comment by Oryss** [comment]
I see!

Seems like [the library used for linting json does not support comments](https://github.com/zaach/jsonlint/issues/50), not sure about how to implement this change but there are libraries that support it

**Comment by n00o** [comment]
I made a branch that modifies the JSON linter to strip all comments and replace them with spaces so that it no longer shows up as an error. This seems like the best course of action since you can still send JSON data that has comments.
https://github.com/n00o/bruno/tree/bugfix/JSON-Linting-Comments

If you would have time to test it @pove, let me know if it good enough for a pull request.

**Comment by pove** [comment]
> I made a branch that modifies the JSON linter to strip all comments and replace them with spaces so that it no longer shows up as an error. This seems like the best course of action since you can still send JSON data that has comments. https://github.com/n00o/bruno/tree/bugfix/JSON-Linting-Comments
> 
> If you would have time to test it @pove, let me know if it good enough to fix this bug.

Thanks @n00o. Can you take a look at this #396? I see we are already using decomment library in bruno-cli. But I also see that strip-json-comments library is ligther and more updated. @helloanoop, can you help us with this?
