### ISSUE TITLE
[Bug] Empty variables shown as red in address bar

### ISSUE THREAD

**Issue by timo-abele** [usebruno/bruno#1022]
## Problem:
An empty variable is shown as red in the address bar (indicating an error), but an empty variable can be intentional.

## How to reproduce:
1. in the environment, define two variables:
my-host=http://localhost:8080
my-base-path *leave empty*

2. in the address bar write {{my-host}}{{my-base-path}}/info

{{my-host}} will be highlighted green for 'works' and hovering the cursor over it will show the value.
{{my-base-path}} will be highlighted red for 'error' and hovering the cursor over it will not show the value.
The address will resolve correctly, so this is only a display issue.

## Context:
My service has a non-empty basepath when deployed, but when run locally the basepath is empty.
In Postman there was no such 'warning' when using empty variables.

## Proposed solution:
Since hovering over variables already shows their value, the appearing infobox should be warning enough to to user who might have left the value empty unintentionally. The infobox should either be empty, or show e.g. '\<empty\>' in italics to avoid confusing it with the possible value '\<empty\>'.

**Comment by helloanoop** [comment]
I believe keeping the red highlight is important since most users rely on a clear visual cue to spot unset variables. Removing it could cause confusion, even if the tooltip shows <empty>. Highlighting ensures users don’t miss an unintentionally empty variable.

Open to revisit this if there is broader community interest in changing the behavior
