### ISSUE TITLE
Requests Exist in Filesystem, but not in application

### ISSUE THREAD

**Issue by joshbrownSB** [usebruno/bruno#1075]
As of today, after an upgrade to OSX Sonoma 14.1, new requests do not persist in the UI, despite being there in Finder. The only visible requests are those that were imported from a Postman collection.

![image (40)](https://github.com/usebruno/bruno/assets/54587017/e0d56f91-ca41-4e41-9f5e-ba8323d95560)

**Comment by n00o** [comment]
The requests are not showing up in the UI because the imported requests don't pass all the `.bru` validation checks. 

Currently the easiest way to figure out what is creating the error is to open a dev environment using the steps found here: https://github.com/usebruno/bruno/blob/main/contributing.md and look at the output coming from this command: `npm run dev:electron` as it looks through all requests and adds a watcher to them. If there are errors then it gives a descriptive reason why it failed.

The other solution would be to remove a section at a time from the `.bru` files using a text editor until it works to help diagnose what is going on. At some point there should be a UI feature to show when `.bru` files were not imported correctly with an `X` next to the request name and an indicator telling you what is not correctly formatted according to the validator.

**Comment by sanjai0py** [comment]
Closing this issue as stale or with insufficient information provided. Please open a new issue if the bug still persists.
