### ISSUE TITLE
Unable to see request in collection 

### ISSUE THREAD

**Issue by akshat-khosya** [usebruno/bruno#1196]
1. I have copied one of the collection folder along with its bru files.
2. So these request are not shown in collection.
3. Also when I am creating new request its file is being creating but unable to see request in collection.
[Screencast from 10-12-23 09:35:36 PM IST.webm](https://github.com/usebruno/bruno/assets/76739180/10bad339-2396-4154-9017-1e8236f1304e)

**Comment by higherorderfunctor** [comment]
I had the same issue today.  Try running from the CLI to see if there are any errors not getting raised to the UI.

Turns out I had too many open file descriptors.  Been messing with my neovim/tmux/terminal config for a couple days without restarting which is the most likely cause.  After I exited out of all my terminals and tmux sessions, Bruno started working again.

**Comment by akshat-khosya** [comment]
I was working on a feature to clone collections. After successfully creating new cloned folder and copying the files related to config and bru. But this turn out to be like this. After restarting electron and nextjs it working fine. Will there a way that do not happen or I can fix that.
[Screencast from 11-12-23 02:11:38 AM IST.webm](https://github.com/usebruno/bruno/assets/76739180/eaad82d1-5f83-4fce-b420-f8148d314760)

**Comment by bpoulaindev** [comment]
By any chance do you have any auth with a "%" character in you password within your requests ?

**Comment by akshat-khosya** [comment]
No
