### ISSUE TITLE
Top Level await throws error in Codemirror editor

### ISSUE THREAD

**Issue by cheleb** [usebruno/bruno#1214]
Using await / async in Test raise error in IDE, whereas working in CLI / UI run.

`tests {
 await test("should have unchanged _info", async function() {
    var _ = require('lodash');
    const data = res.getBody();
    
    const nonRegURL = 'http://localhost:8080/_info';
  
    const axios = require('axios');
  
    let p = await axios({
      url: nonRegURL,
      method: 'get'
    });
  
    assert.deepEqual(data, p.data, "WTF");
  
  });
}`

![image](https://github.com/usebruno/bruno/assets/378539/a6139a67-81f8-4b4a-a311-7a61068de1f8)

**Comment by RicardoVizcaya** [comment]
I also wanted to raise this issue, so plus one from me.
![grafik](https://github.com/usebruno/bruno/assets/119726103/d6a4e221-cb75-4b2a-b2b6-50a5381dbfd5)

**Comment by sahidshaikh23** [comment]
I want to solve  this  issue can u add me please

**Comment by helloanoop** [comment]
@sahidshaikh23 That'd be great!
Currently there is no process to assign the issues.

You can go ahead and work on it. Please raise a PR once ready.

**Comment by helloanoop** [comment]
I confirm the errors due to top level await

<img width="709" alt="image" src="https://github.com/usebruno/bruno/assets/9350733/18e21978-55ce-4adf-9d7c-2b2d7a241aac">

This is because, codemirror uses jshint, and currently jshint does not have an option to disable errors due to top level await.
See https://github.com/jshint/jshint/issues/3447

I am going to push a temporary fix (until jshint support arrives) by making updates to the codemirror javascript linter.

**Comment by cheleb** [comment]
Thank I tried to understand/find a fix, but as a scala backend, my js knowledge clearly lacked

**Comment by helloanoop** [comment]
No worries @cheleb! I have taken care of this.

The fixes are now available in `v1.6.1` 🎉🎉
