### ISSUE TITLE
bruno-cli does not respect the --env option

### ISSUE THREAD

**Issue by TimSusa** [usebruno/bruno#1255]
I gave it now several tries, but in every case the bru cli does not want to respect, what I already set in the desktop app as working env. On the commandline it just does not work as I have suspicion it just ignores the correct environment. 

bru run --env local

--> the local env is ignored in every case, it only works if I set the vars hard to the bru file itself, which is not what I wanna have.

**Comment by DmitryIT** [comment]
same for me

**Comment by DmitryIT** [comment]
Hi @helloanoop,   it happens when I set a variable as a secret.
Then I can still run request using GUI, but CLI calls with bru fail.

bru 1.3.0

![image](https://github.com/usebruno/bruno/assets/4894554/284cdf35-c4b7-4d45-915d-a5ce46f695de)
![image](https://github.com/usebruno/bruno/assets/4894554/e3288404-cb01-47f2-bade-6e80a4b0a313)

CLI call fails, the X-Name header was not sent, 400 - bad request is returned:
![image](https://github.com/usebruno/bruno/assets/4894554/a80ee50c-4352-48ae-bd42-0b4ee54fb989)

It happens only if a variable set as a secret.

**Comment by koljatm-edeka** [comment]
I have the same problem, but with all environment variables that contain a dot, e.g. pcs.url -> ignored; pcs_url -> works

**Comment by glen-polo** [comment]
I'm having same problem as well. It doesn't work for me for _ though.  I have a pre-request script for jwt that works normally but can't get it working with --env <myEnvironment>
