### ISSUE TITLE
cli not sends header

### ISSUE THREAD

**Issue by valihan** [usebruno/bruno#1392]
Hi.
Bruno is cool tool, thank you.

I made tests and it works in bruno.
  1. fetch token (with auth:basic)
  2. get information (with token in header)
All tests are pass in.

But this test don't work in cli.
bru run . --env NPL --output test_output.json

I see token in header in output-file but gets error 401 - Unauthorized.
I tried add authentification in second test (get information) and it's pass.

bru version 1.3.0
bruno version 1.6.1

**Comment by mj-h** [comment]
This is strange --  the same scenario works for me (same bruno / bru versions).

**Comment by valihan** [comment]
Yes, I pass.

I tried add "set-cookie" from first respone but without changes:

      "request": {
        "method": "GET",
        "url": "https://...",
        "headers": {
          "X-Csrf-Token": "W87iD4BWnxSfY02DMwZmgQ==",
          "set-cookie": "sap-usercontext=sap-client=001; path=/,MYSAPSSO2=AjQxMDMBABhUAEUAUwBUACAAIAAgACAAIAAgACAAIAACAAYwADAAMQADABBOAFAATAAgACAAIAAg
        }
      },
      "response": {
        "status": 401,
        "statusText": "Unauthorized",

**Comment by mj-h** [comment]
On small thing: Header names are usually not case sensitive, but it might be safer to use `Set-Cookie` rather than `set-cookie`.

I checked the behavior for `Set-Cookie` and `set-cookie` with hardcoded values, variables and env-variables, both using UI and CLI, using wireshark (to be extra sure that the protected header "Set-Cookie" is not gobbled up by any high-level libraries. I could not recreate any issue. The header field is sent correctly. 

Maybe you can try wireshark as well?

**Comment by valihan** [comment]
I compared works cli and gui and found problem with cookie. 
I changed fetching token

```
script:post-response {
  const sToken = res.getHeader("x-csrf-token");
  bru.setEnvVar("XCSRFToken",sToken)
  const cookie = res.getHeader("set-cookie");
  bru.setEnvVar("cookie",cookie[2])
}
```

And header-part of second request
```
headers {
  X-Csrf-Token: {{XCSRFToken}}
  cookie: {{cookie}}
}
```

Then the test in cli works.
The gui sends the cookie itself without this code
