### ISSUE TITLE
Import Pre Request Scripts and Tests while importing Postman Collection

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#144]
Bruno should import Pre Request Scripts and Tests while importing Postman Collection

**Comment by armand-janssen** [comment]
@helloanoop I have created the import for the 'pre request scripts' and 'tests' in this branch: https://github.com/armand-janssen/bruno/tree/feature/144-import-postman-scripts. 

The implementation now only imports the scripts 1-on-1. 
By default the scripts can't work, because postman has different objects.

How far should the script go in trying to (String) replace the scripts?

Example:
```
const jsonData = pm.response.json();
pm.environment.set("sessionId", jsonData.sessionId);
// could be
bru.setEnvVar('sessionId', res('sessionId'));
```

Code like:
```
pm.test("Response code is 200", function () {
    pm.response.to.have.status(200);
});
// could be
test("Response code is 200", function () {
  expect(res.status).to.equal(200);
});

```
But these are simple examples and the js scripts can get very complicated. 
As an end user I would expect either that nothing is merged or all, to avoid confusion.


So my question:
Is the 1-on-1 good as a first version of this feature and later maybe a new feature to parse the js scripts to be as compatible as possible?

**Comment by armand-janssen** [comment]
Am I assuming correctly that this issue can be close this since https://github.com/usebruno/bruno/pull/711 was released in 0.27 ?

**Comment by srikanthlogic** [comment]
I think this can still be open. While pre-request / tests are imported at request level - Collection level defaults - Headers, Auth, Script, Tests, Proxy - are all empty.  Assuming bruno uses the same overriding preferences of global / collection level / request level setting - for each execution - this breaks importing collections with collection-level pre-script / tests to run.

![image](https://github.com/usebruno/bruno/assets/126862/ff5d5183-8efe-4a81-8ebc-d5726bf427cb)

**Comment by helloanoop** [comment]
Bruno now supports importing scripts and tests (Folder Level and Collection Level) while importing collections.
Closing this issue.
