### ISSUE TITLE
Golden Edition Popup cut-off on dark theme

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#1452]
![GoldenEditionPopup](https://github.com/usebruno/bruno/assets/44080743/d0f00287-975a-4576-a919-fa65432cae09)

when we see the golden editio popup in dark theme 
feels edges cuts off

**Comment by CRAZy-Monk3Y** [comment]
Hello @sseenivasan89, can you please confirm which version you are using? 
I have 1.6.1 release, there this issue is present. (Using on Windows 11 )
I have checked for latest dev version this issue is not present as below image. I think in the next release this will get fixed.
![image](https://github.com/usebruno/bruno/assets/61090388/4d039f9a-3b8a-45c4-96e7-42919ac69fb9)

**Comment by sseenivasan89** [comment]
Hi @CRAZy-Monk3Y 

Check the version below 

![image](https://github.com/usebruno/bruno/assets/44080743/ad13424e-7c59-4404-a30c-a518c0f40567)

**Comment by martinsefcik** [comment]
Should be already fixed in #1358 but not yet released, so wait for next release

**Comment by sanjai0py** [comment]
Closing this as the [PR](https://github.com/usebruno/bruno/pull/1358) that fixed the bug has already been merged and released in [v1.7.0](https://github.com/usebruno/bruno/releases/tag/v1.7.0)
