### ISSUE TITLE
tabler-database-icon is missing when the environment name is too long (max length of 50) 

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#1459]
when the environment name is too long (max length of 50) the table database-icon is missing for those names

![image](https://github.com/usebruno/bruno/assets/44080743/d8a47d87-589f-4736-9490-2830e03692dc)

**Comment by CRAZy-Monk3Y** [comment]
The problem seems to be cause by the icon being resized due to large text. I have implemented an approach where we simple strip the last characters if the name text is bigger than 35. Another approach will be to decrease the font of the text/ using multi line. Any suggestion is much appreciated.
![image](https://github.com/usebruno/bruno/assets/61090388/eb6210c2-46c1-416c-a175-32fea79e4783)

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/issues/1458) fixing the issue has already been merged!

Thanks @sseenivasan89 for taking the time to report these bugs. Your reports greatly help Bruno to improve!
