### ISSUE TITLE
Windows Security got a hit on Vigorf.a (trojan)

### ISSUE THREAD

**Issue by schteffy** [usebruno/bruno#1547]
Hello everyone,

I have installed Bruno on a company laptop (installed manually, not through a company portal). Windows Security has detected and blocked a potential threat. Check out the image below:

![image](https://github.com/usebruno/bruno/assets/113780583/130d482a-107c-4410-8f6b-81c3004799a3)

I did some research and it seems like this alert could be a "false positive". Still, I was wondering if any of you have seen this before? Do we need to worry about it or can we ignore it?

Thanks!

**Comment by helloanoop** [comment]
Hey @schteffy This is a false positive.

The reason why the warning could have triggered is due to the scripting feature of Bruno. You can execute pre-request and post-request scripts in Bruno.

Windows might have flagged this as a potential threat because it is not a common behavior for a desktop application to execute scripts.
