### ISSUE TITLE
Introspection for graphql not working

### ISSUE THREAD

**Issue by mato-gallardo** [usebruno/bruno#1707]
Error occurred while loading GraphQL Schema: Error invoking remote method 'fetch-gql-schema': TypeError: Cannot read properties of undefined (reading 'session')

Love the product!! Having this error while trying to instropect my schema.

**Comment by darcien** [comment]
I encountered similar issue when introspecting:
```
Error occurred while loading GraphQL Schema: Error invoking remote method 'fetch-gql-schema': TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```

Is there a way to get the stack trace or more verbose output of Bruno so we can get more details?

The GQL server I'm trying with is a private company server, so I can't share it.
But I can reproduce it using some demo GQL server from [Hasura](https://demo.hasura.io/).

Like this one, https://learn-graphql.demo.hasura.io/v1/graphql, introspecting it will give the same error message.

**Comment by jam3smay** [comment]
It seems this may have been introduced in v1.3.0. I'm getting the same error with v1.3 and 1.3.1. However, if I revert to v1.2.3 then schema loading via introspection works.

**Comment by datenzar** [comment]
Same here for 1.13.1

Besides that, it's a great product! Buying the gold license was a no-brainer to me!

**Comment by darcien** [comment]
This might sound weird, but introspect works on dev build.
i.e. follow [local development steps to build bruno](https://github.com/usebruno/bruno/blob/main/contributing.md#local-development)

I'm guessing the `ERR_INVALID_ARG_TYPE` is thrown by `Buffer.from` somewhere in [`fetch-gql-schema` handler](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/index.js#L728).
But I couldn't debug further since it's not reproducible in dev build.

Also, I'm not sure if this is related or not, but the `node` version in my Bruno says `16.16`
![image](https://github.com/usebruno/bruno/assets/19742419/e1b7464d-7d36-417b-98f3-6ea5a503ecff)
Even when running the dev build, which uses v20 right now.

**Comment by kimnilsson** [comment]
Can confirm downgrading to 1.12.3 fixes it.

**Comment by AndreKR** [comment]
Still there in v1.14.0.

> Error occurred while loading GraphQL Schema: Error invoking remote method 'fetch-gql-schema': TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

**Comment by GNevsky** [comment]
Same issue for my GraphQL server. 
That only stops me to switch from Postman to Bruno right away.
Bruno 1.14.0/Windows 11

**Comment by sanjai0py** [comment]
Fixed! The patch with the fix will be available soon. Thanks for reporting the issue.

**Comment by kimnilsson** [comment]
Just upgrade to v1.16.1 and it's indeed fixed - thanks!
