### ISSUE TITLE
Can't install in Arch Linux from user repository

### ISSUE THREAD

**Issue by Vanclief** [usebruno/bruno#1772]
When installing from the [user repository ](https://aur.archlinux.org/packages/bruno), it crashes before opening with this error:

`/usr/lib/electron21/electron: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory`

Not sure if this issue should be raised on the user repository, but it may be that bruno is using a old version of the icu library. For anyone who is trying to install it, `bruno-bin` works perfectly as it includes its own version of electron.

**Comment by sanjai0py** [comment]
Hey @Vanclief. The error message looks familiar. Can you please try this #1201

**Comment by vbouchaud** [comment]
Hi there,

`bruno-bin` and `bruno` PKGBUILD maintainer here, I just checked again and the package built from those PKGBUILD should be working fine.

My best guest is you might have the habit of making partial upgrades: the logs you provided show a libicui18n in version 72, however archlinux repositories started providing more recent version (73 then 74) [since may 2023](https://gitlab.archlinux.org/archlinux/packaging/packages/icu/-/commit/91e310f6ff6fc11dacaf676544bdcfa176698754#9b9baac1eb9b72790eef5540a1685306fc43fd6c_7_5).

I believe that if you fully update you system you will be able to have this working.

**Comment by FraCata00** [comment]
If you manually install the `electron21` package, could you install bruno?

```shell
sudo pacman -Syu electron21
```

**Comment by mawkler** [comment]
I'm having the same issue and I have electron21 installed. However, when I run `electron --version` it outputs `v28.2.5`. Could that be the problem? How do i tell pacman to use v21 instead?

**Comment by mawkler** [comment]
@vbouchaud Installing eletrcon21-bin solved it for me. Thank you!

**Comment by vbouchaud** [comment]
I suggest this issue be closed: bruno was upgraded to electron31 which is, for now, the latest electron version available.
