### ISSUE TITLE
Premium License cannot be activated because of certificate error

### ISSUE THREAD

**Issue by nanuit** [usebruno/bruno#1885]
I cannot active my premium license. When i try to do so i get an certificate error 

![image](https://github.com/usebruno/bruno/assets/503026/db01f3e6-cb5c-4d0a-8aae-e8e54355f93e)

the SSL/TLS Verification setting does not work for the activation

**Comment by andre-c-alves** [comment]
same here

**Comment by sanjai0py** [comment]
The License-related bugs/issues are fixed in the latest release. Please open a new issue if the issue persists!

**Comment by helloanoop** [comment]
@nanuit @andre-c-alves Hope your issue is solved.

Attaching a gif here showing how to disable SSL validation to get past this issue.
Please re-open this issue if you are still not able to reinstall the license.
Also you can write to us at support@usebruno.com

![bruno-license](https://github.com/usebruno/bruno/assets/9350733/5b01bed8-cfc2-49a1-97c5-c9ce50911e79)
