### ISSUE TITLE
setNextRequest function run in infinite loop

### ISSUE THREAD

**Issue by RenardFestif** [usebruno/bruno#1899]
I experience some behaviour with the `bru.setNextRequest("name")` function that I think should be addressed 
Context: 
I've created a sample of 4 `GET` Methods with one of them in a different subfolder (cf screenshot)

![image](https://github.com/usebruno/bruno/assets/26570586/c6976d35-98e3-4dec-86ba-4a3fb514b94b)

The request are ordered from 1 to n and initially we expect those request to be executed in sequence in that specific order when we run the collection

Introducing the setNextRequest function as follow 

- Get 1 -> pre-request script `bru.setNextRequest("get 3")`
- Get 2 -> NOTHING
- Get 3 -> post-request script `bru.setNextRequest("get 2")

With this I'm expecting to see the following execution flow 

Get 3 > Get 2 > Get 1 > Get n

**However the observed behaviour is a Loop between Get 2 and Get 3**
![image](https://github.com/usebruno/bruno/assets/26570586/042da98b-a59a-4a9b-b273-d0f21aa05e86)

This can be worked arround with `bru.setNextRequest(null)` as a post-request script in Get2 but this would prevent Get N to be executed

**Comment by mjhcorporate** [comment]
The `setNextRequest` function only influences where the request-runner will "jump" to _after_ the current request has finished processing. 

I think originally I only made `setNextRequest` available in the post-request script, or at least I wanted to, but currently you can also call it in the pre-request script. 

The behavior you want is super tricky to implement when you think about the output on the CLI, because it leads to "nested" requests. I agree that it would be nice to have, but the problem was too tough for me. Insomnia works a little bit that way, but I think there is a reason why Insomnia does not have a good CLI-runner...

A possible workaround would probably need these two steps: 
- have a dummy request `"Get 0"` that executes `.setNextRequest("Get 3")`.
- in the "Get 2", conditionally execute `setNextRequest("Get 4")` to jump past "Get 3" if the loop should be exited

I know this is not ideal, and there are several discussion around introducing different semantics (including nested requests!), but I need to do some digging to find them all...

**Comment by RenardFestif** [comment]
@mjhcorporate Thanks for your feedback, 
I've actually thought of a quite similar workflow/workaround as you presented where I give to the CLI a specific request as an entrypoint and then jump from request to request in a predefined order using `setNextRequest` until the final one where the parameter of the function is set to `null`
But yes I can imagine that these implementation can easily become a nightmare thinking of all the different use-cases there can be ! 

I think in that case this issue can be closed ?
