### ISSUE TITLE
Ignored folders not ignored (maybe windows only)

### ISSUE THREAD

**Issue by panda7789** [usebruno/bruno#1928]
I added into config this ignore settings:
![image](https://github.com/usebruno/bruno/assets/6593380/b7bfec19-fb7d-4661-ad3a-b0c17789c9a3)
But folder is not ignored.

I debugged it and problem is in this two lines:
![image](https://github.com/usebruno/bruno/assets/6593380/62ed6bd5-4cb6-4c98-b137-c5e69f672a1c)
Path is correctly normalized and \ is replaced with /.
But then relative path is made and it again contains \ instead of /.
![image](https://github.com/usebruno/bruno/assets/6593380/1c017e64-2097-47e2-8594-c75926a3e8dd)

**Comment by vaughnbuttiw** [comment]
I think I have a related problem which I suspect is caused by the mapping not handling network drives on Windows.

I'm using the Bruno Desktop App version 1.34.2, running on Windows and accessing a collection on my WSL with a Location of `\\wsl.localhost\Ubuntu\home\beebs\workspaces\techniques\bruno-oauth\Demo-Auto-Token-Cache`.

In the Bruno Desktop App gui, I can see `.git` listed as a folder even though it is also configured as an Ignored file as per:

```
{
  "version": "1",
  "name": "Demo-Auto-Token-Cache",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ],
  "presets": {
    "requestType": "http",
    "requestUrl": ""
  }
}
```

![image](https://github.com/user-attachments/assets/c47dd0cb-2c78-4a60-b83d-237d8b1f175a)

Actual : `.git` directory is shown in the Collection even though it is listed as an ignored file.
Expected : `.git` directory is not shown in the Collection because it is listed as an ignored file.
