### ISSUE TITLE
OAuth 2.0 Client credentials not working via GUI

### ISSUE THREAD

**Issue by viveknz76** [usebruno/bruno#1976]
### Discussed in https://github.com/usebruno/bruno/discussions/1970

<div type='discussions-op-text'>

<sup>Originally posted by **viveknz76** March 31, 2024</sup>
I tried using OAuth 2.0 client credentials (gui) in the latest version but I get the following error when I click "Get Access Token"

{
  "error": "RESTEASY003065: Cannot consume content type"
}</div>

**Comment by bw-hro** [comment]
I have the a similar issue with 1.12.3. It seems bruno sends the oauth request as json content. But standard requires it to be send as url form encoded (https://www.rfc-editor.org/rfc/rfc6749). 

There exists a draft for a json oauth request (https://tools.ietf.org/html/draft-richer-oauth-json-request-00) but this is not supported by all oauth servers. BTW Brunos oauth json request is also not valid to this draft, as it does not convert scope value to list of strings ( ... "scope": ["read","write"] ... vs  ... "scope":"read write" ...)

It looks as if this should have already been fixed in #1701 But somehow it is not part of v1.12.3?

**Comment by elsewhat** [comment]
Same issue as https://github.com/usebruno/bruno/issues/1938

See also comment on merged pull request
https://github.com/usebruno/bruno/pull/1701#issuecomment-2036755440

**Comment by helloanoop** [comment]
This will go out in the 1.13.0 release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.

**Comment by sanjai0py** [comment]
I am closing this issue as it has already been resolved.
