### ISSUE TITLE
Postman Collection level variables are not imported as Collection variables in Bruno

### ISSUE THREAD

**Issue by DanaEpp** [usebruno/bruno#2013]
## Issue
When importing a Postman collection that includes collection-level variables, they are not imported as collection-level variables in Bruno. They actually get lost.

## Workaround
For now, my only solution was to create a new Environment and migrate the vars there. However, this is fragile as it now requires me to remember to set the environment every time I start Bruno since they aren't kept with the collection.

## Expected Behavior
Postman Collection variables should import directly to collection variables in Bruno.

**Comment by ReenuBairi** [comment]
Hello..
Would be great if this can be supported soon. Currently i cannot test any request underneath the collection, as I heavily use variables from the collection level in requests underneath it.
Thanks, 
Reenu

**Comment by mikewagnercmp** [comment]
Adding to this - Trying to migrate from Postman. my collection variables are not coming over either. Tried exporting as a 2.0 and 2.1 collection from postman and no luck.

**Comment by matheusalxds** [comment]
You should follow the env var import documentation, it works for me.
https://docs.usebruno.com/get-started/import-export-data/postman-migration#environment-export

**Comment by helloanoop** [comment]
Just merged the PR. This will go out in `v1.37.0` release.

**Comment by mikewagnercmp** [comment]
Thank you

**Comment by RedVelocity** [comment]
Hi,

I'm currently on v2.1.0 and the collection variables are still not being imported from Postman.

**Comment by anusree-bruno** [comment]
The collection variable isn't being imported when the key contains spaces or special characters. This is because Bruno currently only supports variable names that contain alphanumeric characters, as well as "-", "_", and ".".

Our team is investigating a solution, aiming to translate these variables to a supported format and notify users after the import.

In the meantime, a workaround is to manually edit these variables to use supported characters in Bruno.

Also @RedVelocity can you confirm this is the scenario you are facing?
