### ISSUE TITLE
Issue with Parameters Passed in the URL

### ISSUE THREAD

**Issue by Chibane690** [usebruno/bruno#2124]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I added a parameter "q" directly into the URL bar to be executed without going through the query array as illustrated in the image below:

![Capture](https://github.com/usebruno/bruno/assets/80396129/4862498c-248b-4038-a89c-af5fafd02966)

When I added another parameter from the query array, in my case it was the "options" attribute with the value "concise", it modified the value of the "q" attribute that I associated at the beginning, which caused a bug as illustrated in the image below:

![Capture2](https://github.com/usebruno/bruno/assets/80396129/27349e66-866a-4ed4-8494-c2a6c8c5cfba)

### Screenshots/Live demo link

![Capture](https://github.com/usebruno/bruno/assets/80396129/2f904355-063e-47e4-a314-3e8a053f5e1c)
![Capture2](https://github.com/usebruno/bruno/assets/80396129/8513fbdc-ab83-461e-95a0-05490227de22)

**Comment by Gruummy** [comment]
Are you sure that your uri .... parameters are formed correctly ?

[URIs include components and subcomponents that are delimited by characters in the "reserved" set. These characters are called "reserved" because they may (or may not) be defined as delimiters by the generic syntax, by each scheme-specific syntax, or by the implementation-specific syntax of a URI's dereferencing algorithm. If data for a URI component would conflict with a reserved character's purpose as a delimiter [emphasis added], then the conflicting data must be percent-encoded before the URI is formed.](https://www.rfc-editor.org/rfc/rfc3986#section-2.2)

I think you have a problem with the "==" in your string. The "sign" is a reserved sub-delim character
... and you need to do the percent-encoding / url-encoding

https://www.rfc-editor.org/rfc/rfc3986#section-2.1

Probably Bruno is not handling / showing the data for this reason not correctly in your first screenshot

**Comment by pietrygamat** [comment]
I think this is a serious bug and important feature to fix, but it comes with a bunch of design decisions to make. The URL field should probably validate it's contents and notify user if the value is not correctly formatted URL - and what @Chibane690 inputs is in fact invalid. 

Is bruno supposed to silently try to url encode the value of URL field? What request is actually being sent from this example? What if loading a bru file where the params section does not match url section? Which takes precedence? It would be nice to have an input from maintainers (@helloanoop) on their vision for this, so someone could pick this up. 

A UI solution in this particular case would look something like this:
![params2url](https://github.com/usebruno/bruno/assets/2108093/05de1143-667a-49a1-be57-1c0a2a0bca60)
![url2params](https://github.com/usebruno/bruno/assets/2108093/10411dcf-8b97-42e3-96bf-bbf17292aed6)

**Comment by Chibane690** [comment]
I downloaded the Postman client to perform the same test, and it worked well. It escaped the quotes but not the "==" when sending the request, rather than during inputting the request. 

Here's a screenshot illustrating the request input: 

![Capture8](https://github.com/usebruno/bruno/assets/80396129/a6ff5046-2d21-4a39-8042-dad111e34ab6)

And here's the image during the request emission: 

![Capture7](https://github.com/usebruno/bruno/assets/80396129/bc2aa7fe-0671-45e6-a6ff-863a8a04cbea)

The execution went smoothly without any bugs.

**Comment by helloanoop** [comment]
Just merged the PR #2139 from @pietrygamat 
This will be available in the upcoming `v1.28.0` release
