### ISSUE TITLE
exclamation

### ISSUE THREAD

**Issue by Latnok** [usebruno/bruno#2193]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

An error occurred while creating the collection

when create collection in location with exclamation in path

### Screenshots/Live demo link

![2024-4-28 14-56-53](https://github.com/usebruno/bruno/assets/2025723/c447de15-70a0-4157-afea-c35dc3a84c7b)

**Comment by melroy89** [comment]
Could be Windows... Which is still loosely based on DOS.

**Comment by VolandSZ** [comment]
I have same problem. And i have Windows as my daily driver. But due to limitations i need Bruno collection folder to bi in folder with "!" in its name. Windows in general doesnt have problems with special characters in folder names. I suppose problem lies in Bruno. And it is very sad problem - cant even start using program.

**Comment by melroy89** [comment]
In the meanwhile try Linux. But yea very strange issue.

**Comment by helloanoop** [comment]
Just merged the PR. This should go out in `v1.37.0` release.
