### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#224]
User should be able to use proxy at the collection level and app level

Tasks

- [x] Store Collection Proxy Settings in `bruno.json`
- [x] Electron layer updates to pickup apply proxy settings
- [x] Bump axios at electron layer to 1.5 
- [x] UI support for configuring proxy settings
- [x] CLI support for using proxy settings
- [x] Bump axios at cli layer to 1.5 
- [x] Use proxy config in collection runner in UI
- [x] socks5 proxy support
- [x] Support for proxy bypassing by hostname
- [x] Proxy settings at app level.
- [x] Use OS proxy configuration if found https://github.com/usebruno/bruno/issues/224#issuecomment-1753076833

Below is the axios config to use proxy
```
proxy: {
    protocol: 'https',
    host: '127.0.0.1',
    // hostname: '127.0.0.1' // Takes precedence over 'host' if both are defined
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  }
```

**Comment by mirkogolze** [comment]
The proxy must only be enabled for the request, if the request URL does not match the proxy exceptions

**Comment by mirkogolze** [comment]
Hi @helloanoop,
I am not sure if proxy support is perfectly placed on collection level. Someone needs another proxy than another developer. So it is in my current project. 
In my eyes it should be a global configuration in Bruno preferences. So everybody can enable it for its personal situation. As it is in Postman.
And the usage of the CLI will mostly be in CI/CD. Here you have different proxy configuration. So the global env Variables `http_proxy`, `https_proxy` and `no_proxy` should be enough. Or I need any other configuration for runtime environment.
And the third thing is. We are currently using `axios` in our custom scripts to run the OIDC authentication request to get a token. So I would need to have access to the proxy configuration inside global object `bru`.

Your are too fast with implementing.

**Comment by helloanoop** [comment]
Hey @mirkogolze !

> I am not sure if proxy support is perfectly placed on collection level. Someone needs another proxy than another developer. So it is in my current project.
In my eyes it should be a global configuration in Bruno preferences. So everybody can enable it for its personal situation. As it is in Postman.

I feel we should support it at both levels.
If a proxy config is defined at collection level, then the runtime uses collection level proxy, else it fallbacks to global proxy config.
This has been asked by community to be supported in Postman - https://github.com/postmanlabs/postman-app-support/issues/4739
What do you think?

> And the usage of the CLI will mostly be in CI/CD. Here you have different proxy configuration. So the global env Variables http_proxy, https_proxy and no_proxy should be enough. Or I need any other configuration for runtime environment.

Yup agreed. We can provide flags to pass proxy config via cli arguments.

> We are currently using axios in our custom scripts to run the OIDC authentication request to get a token. So I would need to have access to the proxy configuration inside global object bru.

If I understand you correctly, you need to use proxy only for one request in the collection right? I think we can support a `req.setProxy()` api so that you can apply proxy only for certain requests. The proxy values can be picked up from env config. I recently added similar functionality to disable redirect-follows at a request level. You can take a look at this issue and commits under it - https://github.com/usebruno/bruno/issues/200
What do you think?

> Your are too fast with implementing.

Yes 😄, This was a bit rushed. Need to slow down.

**Comment by rmueller83** [comment]
For me, the current proxy support does not work.
When I analyze curl and Postman with Wireshark, they both issue a CONNECT request to the proxy server (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT )

But Bruno currently creates a GET request which results in an error page from the proxy.

**Comment by mirkogolze** [comment]
Hi @helloanoop,
please merge https://github.com/usebruno/bruno/pull/468 then I go on with my pull request.

**Comment by Lotti** [comment]
I think it can be cool to have also the ability to use OS proxy configuration (in windows is possible to set a proxy system wide, that most of the applications ignore :D )

**Comment by Tilogorn** [comment]
I found an issue with Node.js + axios concerning Proxy, HTTPS and proper HTTP `CONNECT`. I am technically not deep enough into the topic, but this issue may give more details: https://github.com/axios/axios/issues/4531

Injecting e.g. `hpagent` with proper set proxy configuration into axios as `httpsAgent` solved the issue. 

As I observed the same errors and timeouts in Bruno I got in my own Node.js scripts, I suspect Bruno is also missing such a layer for Proxy + HTTPS. I still have to switch to Insomnia for such edge cases. 

This is not a complaint - more a feature request/raising awareness - because I'd like to move completely to Bruno as soon as possible and it probably doesn't just affect me. :-)

**Comment by mirkogolze** [comment]
Hi @Tilogorn,
I am not sure what you use case is.
When you use the proxy configuration for collections or global configuration all different proxy variations should work. All is implemented with the `httpAgents` (https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/index.js#L144).
Only when you use `axios` directly in your custom scripts you don't benefit of the configuration of the request in ipc/network. Then you must do this for your own.

**Comment by Tilogorn** [comment]
Hi @mirkogolze 

with "my scripts" I was rereferring to a completely different Node.js project that I am developing where I encountered problems with axios connecting to the outside https-world. My company proxy always returned 502/Read Error (Squid). It got fixed by using `hpagent` as `httpsAgent`  (tested `https-proxy-agent` succesfully as well).

As I wanted to execute the same requests in Bruno that I did via code in my project, I set everything up - also the Bruno proxy settings - but I got the same 502/Read Error as ealier in Node.js before injecting `hpagent`/`https-proxy-agent`. That's why I assumed you missed this fix and it would be interesting for you to know about it.

![image](https://github.com/usebruno/bruno/assets/7524854/9892d7f1-5ed8-464b-8563-8de6540c69da)

Now that you showed me [that you already use](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/utils/proxy-util.js#L3) `https-proxy-agent` to work around this issue, I am quite confused why I experience this behavior. 

![image](https://github.com/usebruno/bruno/assets/7524854/48cde875-8404-446c-bb0a-41d649036920)

I am now at a point where my custom Node.js scripts work but Bruno with the same setup does not and I am not sure how to debug that further.

**Comment by mirkogolze** [comment]
When you have time you could try that out with Bruno.
To enable local Bruno development is quite easy: https://github.com/usebruno/bruno/blob/main/contributing.md

You could switch to `hpagent` and try if it is working with your companies proxy.

**Comment by sdepold** [comment]
Is there a way to configured Bruno to use the Web Proxy Auto-Discovery Protocol or Proxy Auto-Config?

**Comment by sdepold** [comment]
Also, how do I opt in for using a proxy for both http and https?

**Comment by wamfous** [comment]
Hi, bruno looks very promising but I currently can't get it to work from behind my corporate proxy. I've tried adding the proxy configuration to global or collection settings but all of my requests time out.
Is there some way to troubleshoot this?
Thanks

**Comment by wamfous** [comment]
Thanks for the quick reply. The console shows two errors directly on startup
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
Error: Error invoking remote method 'renderer:fetch-notifications': Error while fetching notifications!
```
I'm not sure if that can explain anything.
And running from the command line gives a big object dump after the timeout. I won't copy it here but I'm not sure what to look for

**Comment by lanes100** [comment]
> Thanks for the quick reply. The console shows two errors directly on startup
> 
> ```
> Failed to load resource: net::ERR_FILE_NOT_FOUND
> Error: Error invoking remote method 'renderer:fetch-notifications': Error while fetching notifications!
> ```
> 
> I'm not sure if that can explain anything. And running from the command line gives a big object dump after the timeout. I won't copy it here but I'm not sure what to look for

I am running into the same error on startup. It's actually blocking me from making https requests where the certificate is invalid even with SSL verification off. This is a huge bug that needs to get fixed ASAP
See https://github.com/usebruno/bruno/issues/2391

**Comment by wamfous** [comment]
OK, I hadn't explored the HTTPS angle. Here are some new findings:

**GET http://example.com and https://example.com** time out from behind my corporate proxy with the proxy configuration.

**GET http://example.com** works from behind my corporate proxy if I disable the proxy configuration (it shouldn't). Is Bruno using the underlying system proxy configuration?

**GET https://example.com** gives me a 502 "Connection reset by peer" with proxy disabled

**Comment by mirkogolze** [comment]
No. There are no system configuration used. 
There are three ways to use proxy.

1. Configure on global level
2. Configure on collection level to overwrite global configuration
3. use HTTP_PROXY, HTTPS_PROXY, NO_PROXY environment variables. They are used by axios automatically. But this can influence the other settings.

**Comment by dsculptor** [comment]
Can we not save the proxy password in the bruno.json file? 
Is it possible to use a variable from `environment` as the proxy password - if that is the case, then we don't need to invent anything special to avoid leaking proxy password in a git repo.

**Comment by mhimoma** [comment]
I need to not go through the proxy to be able to reach the services, I've used this configuration to disable the proxy for Bruno:
```
"proxy": {
    "bypassProxy": "",
    "enabled": false,
    "auth": {
      "enabled": false,
      "username": "",
      "password": ""
    },
    "port": null,
    "hostname": "",
    "protocol": "http"
  }``
```
But its does not work! Any Idea about how can I set up Bruno to not go through proxy correctly?

**Comment by mirkogolze** [comment]
[axios ](https://github.com/axios/axios) is using the environment variables HTTP_PROXY and HTTPS_PROXY, if present. Please check if the are set on your machine globally.

**Comment by mhimoma** [comment]
Yes they are set globally on my machine along with no_proxy variable.

**Comment by mleziva** [comment]
Hi, to add on to this issue, there is a problem with the CLI and also unexpected (maybe?) default proxy behavior.

CLI:
If the environment variable `https_proxy` is set, axios attempts to use that and requests will fail. This is because the request configuration of the CLI axios client doesn't specify `proxy: false` like the electron configuration. Should be a small change to [packages/bruno-cli/src/utils/axios-instance.js](https://github.com/usebruno/bruno/blob/3cb3f8094f42bf1a743d290283c0feb372f0f522/packages/bruno-cli/src/utils/axios-instance.js#L12)

Default behavior question:
It looks like run-single-request.js only sets the proxy if it is configured in the bruno settings: `const proxyEnabled = get(brunoConfig, 'proxy.enabled', false);` I think it would make more sense if it also checked the `http_proxy` variables and enabled the proxy if those were set as well.

**Comment by helloanoop** [comment]
@mleziva Agree that we need to make changes in CLI to keep it upto date with how the app treats proxy settings. Can you create a new issue specifically for the CLI?
I’m closing this ticket as proxy support has been delivered, and it will be cumbersome to track the nuances around CLI-related proxy issue here.
