### ISSUE TITLE
 For the future:  I hope you won't do the same mistake Insomnia did today

### ISSUE THREAD

**Issue by alinmiron** [usebruno/bruno#228]
The last update is forcing users to register for a cloud account.  Insomnia will lose a lot of their users.... some of them, like me will explore Bruno.

**Comment by l0new4nder3r** [comment]
Postman started the shady moves, Insomnia followed. Thunderclient starts crippling its free plan for the end of September...

Long live Bruno!

**Comment by alinmiron** [comment]
> Postman started the shady moves, Insomnia followed. Thunderclient starts crippling its free plan for the end of September...
> 
> Long live Bruno!

I know, but I also know that Insomnia guys need to monetize it. But I am sure that there was a better way to do this instead forcing everybody to register to cloud and move their projects there. I mean c'mon,  we can't move to cloud sensitive data like credentials, URL schemas and other...
Hope for the best !

**Comment by helloanoop** [comment]
I can understand the community's concern here. We would like to do things differently so that we don't keep repeating history in the API GUI clients ecosystem.

I have penned down some thoughts on Opensource, Sustainability, Privacy, Freedom and Incentives in this [discussion thread](https://github.com/usebruno/bruno/discussions/269)

I look forward to hear your thoughts and perspectives.
