### ISSUE TITLE
Unable to run shell commands from scripts

### ISSUE THREAD

**Issue by akshygupt** [usebruno/bruno#2381]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I keep getting "Command not found" error when running shell commands in scripts. I tried specifying the different shell but nothing works. 

Script: 
```
var {execSync} = require('child_process')
  try {
    console.log(execSync('echo $PATH', {encoding: 'utf-8'}))
    console.log(execSync('where ls', {encoding: 'utf-8'}))
  }
  catch(e){
    console.error(e)
 }
  ```
bruno.json
```
{
  "version": "1",
  "name": "test",
  "type": "collection",
  "scripts": {
    "moduleWhitelist": ["child_process"],
    "filesystemAccess": {
      "allow": true
    }
  }
}
```
Getting the following error
`Error invoking remote method 'send-http-request': Error: Command failed: {command} zsh:1: command not found: {command}`

Bruno: v1.18.0

### Screenshots/Live demo link

![Screenshot 2024-05-29 at 11 50 53](https://github.com/usebruno/bruno/assets/7352401/b9c96bb6-1a5f-4abb-9acb-3317c9d5dcd7)

**Comment by micmeier** [comment]
I had similar issue and finally found a workaround to run shell command using execSync. After some trying i figured out that the execSync command cannot find modules loaded by my .zprofile file (My default shell is zsh). In my case i got the error 

```
Error: Command failed: node script.js /bin/sh: node: command not found
```
while running this line
```
execSync('node script.js')
```

My workaround is to load the profile before running the code:
```
execSync('source ~/.zprofile && node script.js')
```

This seems to fix the issue for me. Hope this help to find the root cause.
