### ISSUE TITLE
Bruno converts decimal numbers in JSON body to strings

### ISSUE THREAD

**Issue by mrtnbrst** [usebruno/bruno#2438]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno converts decimal numbers in JSON to strings as visible in the screenshot.

### .bru file to reproduce the bug

[example.json](https://github.com/user-attachments/files/15788467/example.json)

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/54993850/c9636822-6ec0-40e3-9e58-e3d13c2efc35)

**Comment by mrtnbrst** [comment]
The attached file is a .bru file, but those are not allowed to be uploaded, so I changed the file extension.

**Comment by jwetzell** [comment]
Seems to be an issue with "long" decimals as not all of the decimals in your example got converted to strings.

**Comment by jwetzell** [comment]
The problem is [this line here](https://github.com/usebruno/bruno/blob/3db7d54acad3cccbe8282a2467302824f7241c23/packages/bruno-electron/src/ipc/network/prepare-request.js#L176) for someone looking to fix this. It is using a library to parse the JSON but that library is converting these long decimals into "BigNumber" type. @sanjai0py is the one who added this BigNumber parsing in so might be able to speak to the reasoning or if this side-effect was not known.

**Comment by helloanoop** [comment]
@sanjai0py Can you comment on this?

**Comment by helloanoop** [comment]
This has been fixed as a part of PR https://github.com/usebruno/bruno/pull/2773, and will go out in the v1.27.0 release.
