### ISSUE TITLE
Mouse events are not registered at the bottom of the response window

### ISSUE THREAD

**Issue by schiab8** [usebruno/bruno#2534]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Scroll and click are not being registered when hovering over the bottom section of the response window, at the height where the query-result-filter is located.

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/15898277/0d1282e0-7d0c-46fb-a4e4-b712b81dce1f)

[vokoscreenNG-2024-06-28_20-08-11.webm](https://github.com/usebruno/bruno/assets/15898277/885cc594-0e60-4578-a315-d897707e971b)

**Comment by Aspireve** [comment]
Hey Hi!!

I've been using bruno for some time now (after it was referred to me by some friends) and it seems really cool, but never quite noticed this bug, now I cant unnotice it (lol).

Having a web development background, my guesses are that mostly there is a container covering the text (maybe because of the filter, but not sure though)

Could I try debugging this issue?
