### ISSUE TITLE
folder showing even after deleting 

### ISSUE THREAD

**Issue by not-known-person** [usebruno/bruno#265]
folder inside collection doesn't get remove from the list even after deleting , 
![Screenshot 2023-10-01 145005](https://github.com/usebruno/bruno/assets/134089980/77b2971a-a64d-447b-88aa-e254959213af)
I have deleted the Demo folder in the Demo12389 , but it still showing  ,
but restarting the application fixes the issue .

**Comment by helloanoop** [comment]
Hey @not-known-person Thanks for taking caring of this!

The phantom folder issue is only on Windows. This works perfectly fine in mac and linux. add this [comm
I've just added this [commit](https://github.com/usebruno/bruno/commit/fcc12fb089472716328054665d767d7b0ae48e04) so that this fix is applied only on windows.

On Mac and Linux this might end up with multiple redux updates (like not harmful), but still choosing not to do it since rename and delete feature is pretty stable on mac and linux.

Also, another debugging tip. When you bring up the app, you can open developer tools and turn on debugging by executing `window.__IS_DEV__ = true`

On my mac, as you see below in the screenshots I have 3 IPC events. `addDir` when I added the test directory and upon rename - two subsequent events `unlinkDir` and `addDir` which is basically a rename. I am suspecting you are not seeing this in windows. 

![image](https://github.com/usebruno/bruno/assets/9350733/d6132be2-d553-462c-b0aa-22fd5bad9675)

**Comment by helloanoop** [comment]
This has been released in `v0.16.5`
You can download the latest version from the website.

Thanks @not-known-person 

Closing this issue. Please re-open if the issues still persists.

**Comment by not-known-person** [comment]
Thank you so much for your kind words! It's been a pleasure contributing to the project, and I'm glad I could be of help. I look forward to more opportunities to work together and make the project even better.
