### ISSUE TITLE
Failed to construct 'URL': Invalid URL everytime the URL is modified

### ISSUE THREAD

**Issue by hayden-mumm** [usebruno/bruno#2652]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Every time I modify the URL I get the following error: Failed to construct 'URL': Invalid URL

### Screenshots/Live demo link

Here's the issue
![image](https://github.com/user-attachments/assets/c5fe24d4-a600-4aba-b60a-f50fc14a8094)
Tried this and it did not have the issue
![image](https://github.com/user-attachments/assets/dc13e26f-98e6-47b0-8ff7-10b047695442)

**Comment by hayden-mumm** [comment]
This is still happening in 1.22

**Comment by Its-treason** [comment]
Bruno tries to parse the URL to create the query parameter table in the "Params" tab. But your URL is invalid because of the variable placeholder for the port number. Sadly, I don't have a good fix for you now. Maybe try to create a "Request Var" in the "Vars" tab that combines your hostname and port like this:

![image](https://github.com/user-attachments/assets/505b7385-312d-41fc-8e4b-9a18e5c179f2)
