### ISSUE TITLE
Add a show/hide privacy toggle to passwords and secrets in Auth options

### ISSUE THREAD

**Issue by nataliecarey** [usebruno/bruno#2747]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

**User story**

As a user I want my authentication password/secrets to be hidden by default and visible if I choose to reveal them.

**The use case/reason**

I work on a system where we have to be pretty careful with credentials, I was screen sharing with other developers while trying to make an authenticated API call from Bruno but I couldn't have the password on the screen share at any time.  I ended up setting up the request without the password, disconnecting the screen share, entering the password, making the request, removing the password, starting the screen share again.  I had to do that cycle multiple times which got quite frustrating.

**Related PRs**

 - [Adding a privacy toggle to proxy settings](https://github.com/usebruno/bruno/pull/2127) - the same privacy toggle should be used
 - [Masking support for SingleLIneEditor](https://github.com/usebruno/bruno/pull/2240) - this isn't merged yet but it implements the functionality needed on the element that's used for Auth settings

### Mockups or Images of the feature

<img width="361" alt="Screenshot 2024-08-02 at 10 02 09" src="https://github.com/user-attachments/assets/0bc8cafa-7d11-4f8a-ae5d-ae9990728292">
<img width="368" alt="Screenshot 2024-08-02 at 10 02 16" src="https://github.com/user-attachments/assets/96de28e7-c118-4bea-98aa-320e1bd7fe7a">

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/2750) by you that resolves this issue has been merged into Bruno. Thank you for taking the time to work on this!

**Comment by katzda01** [comment]
In my use case we use different environment variables, and because of this change, it made my life unnecessarily tedious, as I keep having to click on reveal just to see which environment placeholder is used, in order to run the required SSO bearer token request.

<img width="456" height="79" alt="Image" src="https://github.com/user-attachments/assets/3f18c4e1-bdbf-4847-9f4b-15b27a59dba0" />

It would be far better if the default show/hide were set in the configuration so that people who would like this shown by default can have that.
