### ISSUE TITLE
Feature idea: path parameters and test data

### ISSUE THREAD

**Issue by tibeer** [usebruno/bruno#281]
Hi there 👋 

I messed up. There are path parameters already available! Its in the _Vars_ tab, "Pre Request". Still, the section below with "Going one step further" might be of interest ...

~~I thought it might be interesting to have an option to provide path parameters in a UI supported way without hardcoding them.
E.g. imagine an URL that looks like this `https://myapp.com/customers/C100000482/addresses/0001`. This URL includes two "parameters" `C100000482` and `0001`. It would be nice to have them in the same fashion displayed like the query tab.~~

## Use-cases

~~When testing with APIs you do not develop on your own, one might find it very useful to have a "hardcoded" URL with paramters that can be filled with actual test-data, e.g.~~

```
https://myapp.com/customers/{{customer_id}}/addresses/{{address-id}}
```

~~With a parameters gui tab containing:~~

|Name|Value|
|---|---|
|customer_id|C100000482|
|address_id|0001|

~~Of course disabeling the parameters is not very useful.~~

~~It might not even need to be a seperate tab, but might also be included in the "Query" tab: If the variable is enabled, it is a query parameter, if it is disabled it becomes a path parameter for example.~~

## Going one step further

One additional feature might be a drop-down selection list of possible test-values you can define on your own. I have never seen such a functionality somewhere yet but I think this would help a lot. And since every request has its own dedicated file it can probably make things even more "clean" as every request can house its own test-data if desired, at least for path parameters.

Happy to hear feedback on this! 😃

**Comment by darvesh** [comment]
I was a bit disappointed when I came to know that there is no support for path params yet. It would be be good idea to separate path and query params. 

Using {{}} in the URL will conflict with environment variables, right? In my opinion, using `:/address_id` would be better like Postman. In this case, we can specify `{{address_id}}` below.

**Comment by tibeer** [comment]
@darvesh I found it. Go to the "Vars" tab and enter your path parameters in the "Pre Request" section like you do with env variables. 
![image](https://github.com/usebruno/bruno/assets/39375770/fea8043c-bc7e-437e-929a-e68f3dfc056d)

**Comment by darvesh** [comment]
@tibeer that's just using variables though.  I would love to have feature where you can write /:id and specify the id value in the query tab under params

**Comment by ThenTech** [comment]
> Using {{}} in the URL will conflict with environment variables, right? In my opinion, using `/:address_id` would be better like Postman. In this case, we can specify `{{address_id}}` below.

Using an `env` or `collection` variable in the URL directly seems to work, but using a collection variable inside the Pre Request value, does not expand the actual value.

For example:

![image](https://github.com/usebruno/bruno/assets/11493646/42bc700f-6c18-4902-968a-12550adfdc58)

will expand the URL to: `http://.../wo/{{lastWOId}}/` instead of using the ID that the tooltip already correctly shows.

But using a parameter from Query with either `{id}` or `:id` in the URL for example would be more clear. (Provided you can use a variable as the value, that will expand to its value before formatting it in the URL of course).

Thunder Client (which I'm trying to replace) also does this.

**Comment by game5413** [comment]
Hello, i'm challenging myself to create path parameters on bruno because i really liked that feature on Postman. Currently i've finished the feature and try to debug if anything goes correctly, here some preview about what i'm working on.


https://github.com/usebruno/bruno/assets/37659721/70567f7a-ffbb-4bd7-96e0-22b11c9500ee

**Comment by ThenTech** [comment]
@game5413 Looks good

**Comment by darvesh** [comment]
@game5413. Looks amazing. Thank you so much.

**Comment by helloanoop** [comment]
@Its-treason @martinsefcik @lared Let me know if you guys have any comments on this.
Reaching out since its a major functionality, and it'll be hard to make any changes once it gets in.

This can technically be achieved via `vars` too, but I don't see any harm in supporting this. Postman already supports this.
I see benefits in terms of clarity and the user being able to quickly change query and path params in the same tab.

The request `vars` could be used to store anything that goes inside the request json body.

**Comment by game5413** [comment]
> see benefits in terms of clarity and the user being able to quickly change query and path params in the same tab.

Also, it can be used to distinguish value to make easy when to implement generate Open API Spec. Maybe something like this, i've used path parameter to determine field for user input.
![image](https://github.com/usebruno/bruno/assets/37659721/9785878a-6bed-4fe5-8cef-16a3420dbbe6)
then after converted to Open API Spec the path parameter will be readed.
![image](https://github.com/usebruno/bruno/assets/37659721/e4d93440-6676-4102-a3bb-f31d037bfa89)


Right now, i'm still developing the feature for publish Bruno collection into Open API Spec. My top priority right now, was to create feature save response API as example like Postman did. It was helpful i think for make some example return when generating API documentation at Open API Spec.

![image](https://github.com/usebruno/bruno/assets/37659721/9fdb9a3d-5954-4506-a1ff-397eb0ea8173)
![image](https://github.com/usebruno/bruno/assets/37659721/68c30659-a3b2-4d00-9b21-dbe41edb5744)

**Comment by kaiserkiwi** [comment]
This is one of the features that blocks Bruno for us currently. Looking forward to the release where #484 is part of.

**Comment by IceBjerg** [comment]
Hi everyone! 

I would really appreciate this feature, and thank you @tibeer for your awesome work! 
One thing that I would need when using path parameters is that the path parameter should be encoded in my case. 


Currently, I checked the code you provided, started bruno and tried the following: 

1. URL: `http://localhost:3000/myapi/:param1`
2. `param1=abc/cba`
3. The following HTTP request was sent: `http://localhost:3000/myapi/abc/cba`
4. Then i tried modifying `param1=abc%2Fcba`
5. Without save, the following HTTP request was made: `http://localhost:3000/myapi/abc%2Fcba`
6. When saving the tab, param1 immediately changed back to: `abc/cba`
7. Next request is again  `http://localhost:3000/myapi/abc/cba`

I suspect this is not an issue with the path params itself, because I experience the same bug on the "Vars" tab as well, but I wanted to point out that encoding path parameters is my current workflow, and I would love to see either automatic encoding of the parameter, but rather a checkbox next to the path parameter that will be used to turn on parameter encoding. 

What do you think?

**Comment by helloanoop** [comment]
@game5413 Awesome work on the PR.

I am just thinking whether should use `:id` like postman does or use `{id}`

Bruno uses double curly braces to reference all kinds of variables `{{}}`

I don't have a strong opinion on whether to use `:id` or `{id}`.
Given a choice, I would prefer the later since it's used by openapi and Bruno will have ongoing integrations with openapi.

**Comment by tibeer** [comment]
Would also vote for the latter one with curly braces :)

**Comment by martinsefcik** [comment]
@helloanoop Question is if we need to distinguish between path parameters and collection/environment variables. If `{}` will be chooses and in case there will be path parameter and collection/environment variable with the same name defined then which one will be chosen? So probably choosing `:id` can be less painful option.

And also you have to be able to parse URL and to identify path parameters to show them in UI. If `{}` will be chosen then you don't know if intension was to use path param or collection/environment variable => so you don't know if such variable should be displayed on params tab or not.

**Comment by helloanoop** [comment]
> If {} will be chosen then you don't know if intension was to use path param or collection/environment variable => so you don't know if such variable should be displayed on params tab or not. At least Postman is doing this.

@martinsefcik `{{}}`  is for env/collection vars and `{}` would be for path params. There would not be any conflict right?

More thoughts on this:
`/:id` is a common pattern across backend frameworks to parse path params. The other advantage is that the pattern distinguishes itself clearly against the existing `{{}}` pattern in Bruno.

Now, I am siding more towards `/:id` pattern.

**Comment by tibeer** [comment]
Closing this for the time beeing, as we can use double braces to use variables. The other topic with multiple test-data is something for a different feature request.
