### ISSUE TITLE
Request body value gets cut off and stays hidden

### ISSUE THREAD

**Issue by rahulhaque** [usebruno/bruno#2832]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Form request body value gets cut off and stays hidden and cannot be visible by moving the cursor or mouse scroll. See the `cmdContent` value in attached screenshot.

### Screenshots/Live demo link

![Screenshot from 2024-08-14 13-10-47](https://github.com/user-attachments/assets/9401c4d5-2320-4077-9854-b321c7c6b521)

**Comment by zachary-berdell-elliott** [comment]
This bug is due to the css property display: contents; in the StyledWrapper for MultiLineEditor. Changing it to display: block; fixes the issue with the text being cut off. I'll raise a PR and link to this issue.
![image](https://github.com/user-attachments/assets/1c4a3898-85f1-4425-87f4-93eb7acd2681)
![image](https://github.com/user-attachments/assets/8cb2cc4f-a1e4-480e-a96b-565630ad8daa)

**Comment by zachary-berdell-elliott** [comment]
PR raised here: https://github.com/usebruno/bruno/pull/2917

**Comment by helloanoop** [comment]
PR Merged.
