### ISSUE TITLE
Getting output from Bruno CLI request

### ISSUE THREAD

**Issue by ketilyv** [usebruno/bruno#2927]
I'm new to Bruno, but I try to automate some testing. From an outer bash shell script, I call a bru script to POST a document, and in the result ("res.body.id") there is a document ID like this:
```
{
  "id": "0b34e0e2-dae7-40ee-9e37-26627fd00b74"
}
```
Is there a way that I can pass this value to the outer shell script, so I can use it as an environment variable when running a subsequent GET (BRU CLI) request?

**Comment by chrisnagel** [comment]
If the calls and the evaluation are done via Bash anyway, I would output the desired value via `console.log()`.
However, since the bru cli itself also generates output, it would be appropriate to provide the relevant value with a unique prefix and then ignore it as part of the search result.
In your case, the _post-response_ script could look like this:


`console.log("returned-id:" + res.body.id);`

And the bash prompt as follows:

`bru run mycollection.bru | grep -oP '(returned-id:)\K.*'`

The result can then either be 'undefined' (in the event that the response did not contain an object with the corresponding property) or a valid value.

**Comment by ketilyv** [comment]
Thanks - this was helpful, although I ended up with another solution!
