### ISSUE TITLE
[Bug] bruno showing strange behaviour while relocating sub folder and requests by drag and drop 

### ISSUE THREAD

**Issue by AyushNigam-1** [usebruno/bruno#307]
I have added two video regarding the bugs -:
In First Video we can clearly see that :- I had moved DemoFolder-2 to DemoFolder but bruno Ui didnt get update although the DemoFolder-2 had correctly moved to to the DemoFolder , I confirmed it by visiting the windows inbuilt file manager system .
[https://youtu.be/7QNmLpM0_1k](url)

In Second Video - i had moved DemoReq and DemoReq-2 into DemoFolder-2 and then I moved DemoFolder-2 to DemoFolder , and as before Bruno Ui didnt get update , and as soon as I visited the file manager , I founded that DemoFolder was no more there , and both DemoReq , DemoReq2 with DemoFolder-2 had deleted automatically 
[https://youtu.be/nyc8CZ1kAbc](url)

Do watch those video with corresponding description for better understanding , for the sake of simplicity , I had updated the description of both video with their respective bug description 

And Yeah , I AM USING WINDOWS 11 *64

**Comment by helloanoop** [comment]
@lared Please see if you could take a look when you find some time

**Comment by lared** [comment]
@not-known-person I see that you are running v0.16.6, could you please upgrade to the current version?

Can't reproduce on v0.17.0, electron on Ubuntu Jammy.

**Comment by lared** [comment]
Now I did take a proper look, v0.17.0 Ubuntu Jammy.

Issue 1:

1. Create collection `DemoCollection`
2. Add folder `DemoFolder`
3. Add folder `DemoFolder-2`
4. Drag `DemoFolder-2` over `DemoFolder` and drop

Result: `DemoFolder-2` is now inside `DemoFolder` both on the filesystem as well as in the UI


Issue 2:

1. Repeat steps 1-3 above
2. Create empty requests called `DemoReq` and `DemoReq-2` in the root of the collection
3. Drag `DemoReq` over `DemoFolder-2`
4. Drag `DemoReq-2` over `DemoFolder-2`

Result: Both `DemoReq` and `DemoReq-2` are present inside of `DemoReq-2`, both in the UI as well as in the filesystem. There was a momentary flicker between when the move happened, likely because the file watch events were processed separately and a render happened in between.

So all in all, can't reproduce - we will need to narrow it down to version and/or the OS. I might be able to grab a mac when I'm at work.

**Comment by helloanoop** [comment]
Hey @AyushNigam-1 !

Apologies for getting back so late. This issue has been resolved and should not be happening in Bruno anymore.
Please reopen the ticket if the issue persists.
