### ISSUE TITLE
DotEnv variable - Leading zero stripped from value

### ISSUE THREAD

**Issue by emmdel** [usebruno/bruno#309]
Hi,

When using an `.env` file with the following values : 
```
USER_ID=0635613768
USER_SECRET=xxxxxxxx
CLIENT_ID=yyyyyyyyy-7e70-451d-abee-zzzzzzzzzzz
CLIENT_SECRET=xxxxxxxxxxxxxxx
```

And the following request : 
```
meta {
  name: Oauth Login
  type: http
  seq: 1
}

post {
  url: {{site_url}}/oauth/token
  body: formUrlEncoded
}

body:form-urlencoded {
  username: {{process.env.USER_ID}}
  password: {{process.env.USER_SECRET}}
  grant_type: password
  client_id: {{process.env.CLIENT_ID}}
  client_secret: {{process.env.CLIENT_SECRET}}
}
```

The leading zero for `username` is stripped when running the request : 
```
> POST http://hostname/oauth/token
> content-type: application/x-www-form-urlencoded
> data "username=635613768&password=xxxxxxxx&grant_type=password&client_id=yyyyyyyyy-7e70-451d-abee-zzzzzzzzzzz&client_secret=xxxxxxxxxxxxxxx"
```

I tried to quote the value (`USER_ID="0635613701"`), but it seems to break the interpolation : 
```
> POST http://hostname/oauth/token
> content-type: application/x-www-form-urlencoded
> data "username=%7B%7Bprocess.env.USER_ID%7D%7D&password=%7B%7Bprocess.env.USER_SECRET%7D%7D&grant_type=password&client_id=%7B%7Bprocess.env.CLIENT_ID%7D%7D&client_secret=%7B%7Bprocess.env.CLIENT_SECRET%7D%7D"
```
Am I missing something ? 

Note: Using Bruno v0.17.0 on MacIntel, Ventura 13.6

**Comment by lared** [comment]
This is the same as missing leading whitespace when quoted.

The issue seems to be that there's a custom parser for .env files - `packages/bruno-lang/v2/src/dotenvToJson.js`, you can see in `:6` that we're greedily taking whitespace until we encounter value. Then this gets parsed as number in :69, even if the value is only accidentally a number.

I'm not sure why this was done this way, but in "normal" .env grammar this type cast would not take place. 

It's pretty much a design decision whether to :

- keep it as it is in its custom weirdness
- ditch the current format and parsing (which is technically a breaking change if anyone relies on that stripping, parsing numbers or on preserving "s) 
- keep it as it is, or to add support for ""ing strings.

**Comment by helloanoop** [comment]
> just replace it with dotenv.parse

I did consider dotenv. I opted to write a custom one so that we had more control on parsing as is the case with bru lang.
I wanted a simple parser which would parse `strings`, `numbers` and `booleans`. This was due to the nature of our environment settings ui which was a simple key-val editor (with no support in ui for multiline strings)

> what if a user wanted to store multi line strings in the .env file

They should use `\n` and parse the whole string as needed in the `pre-request` scripts

> what if a user wanted to store an array/object in the .env file

`.env`
```env
arr=[1, 2, 3, 4]
```

`pre-request-script`
```javascript
JSON.parse(bru.getEnvVar("arr")
```

> The leading zero for username is stripped when running the request

This needs to be fixed.

> This is the same as missing leading whitespace.

This also needs to be fixed.

> still a breaking change

Most parts are pretty sorted in bruno, Its ok to have minor breaking changes (before v1) which are easily fixable .

#### PS: Some other thoughts

> Do I think designing a custom dsl implementation (bru lang, env parsing) is worth the tradeoff over using an existing standard

The goal of designing the `bru lang` was from a standpoint to make the representation of the request as simple as possible.
So that it can be easily reviewed in git-pr-workflow.
I don't think json and yaml are good for this purpose. The tradeoff is standard vs readability.
I personally think that the readability is more important than the standard in context of Bruno

That said. TOML looks like a perfect fit to replace bru lang. If we are able to get it to work, its the perfect blend of readability and standard that we need. We want to support alternate file fomats. Checkout this discussion: https://github.com/usebruno/bruno/discussions/360

**Comment by helloanoop** [comment]
```javascript
USER_ID=0635613768
USER_SECRET=xxxxxxxx
CLIENT_ID=yyyyyyyyy-7e70-451d-abee-zzzzzzzzzzz
CLIENT_SECRET=xxxxxxxxxxxxxxx
```

> but in "normal" .env grammar this type cast would not take place.

100%. Working on this now.

**Comment by helloanoop** [comment]
@lared @emmdel 
I was wrong. It was a bad idea to do the typecast and reinvent the wheel.

We'll use the [dotenv](https://www.npmjs.com/package/dotenv) engine to do the parsing for us.
Commit: https://github.com/usebruno/bruno/commit/3d366477d043a5438e7f31c7cf8c92f816906bb6

**Comment by helloanoop** [comment]
Noice 

![image](https://github.com/usebruno/bruno/assets/9350733/58b68bc0-754d-4973-b408-40061ce5fb6b)

**Comment by helloanoop** [comment]
This is live in `0.22.1`

@emmdel When you have some time, can you check if the latest version solves your problem?

**Comment by emmdel** [comment]
@helloanoop Tested it today and this is working, thank you 👍
