### ISSUE TITLE
[Bug] More than one auth method can be selected at once

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#358]
To reproduce, create a request and:

1. Set header `Authorization` to `auth header`
2. Go to auth tab, pick `basic auth`, put `user` and `pass` as username and password respectively
3. Switch to `bearer token` and put `bearer` as the value

Expected: only bearer token is saved in bru file (principle of least surprise)

Actual: all three auth methods are saved in bru file, who knows in which order they are applied

**Comment by helloanoop** [comment]
> Actual: all three auth methods are saved in bru file, who knows in which order they are applied

This is by design. Very similar to request body. If an api can accept both xml and json bodies, you can store them in the same request.

If you are using auth, you should not be adding the header `Authorization`. Ideally the expectation should be that auth must override the header.

> who knows in which order they are applied

In the below example whatever `auth` is gets stored inside `get` is applied. 
```
meta {
  name: Basic Auth 200
  type: http
  seq: 1
}

get {
  url: {{host}}/api/auth/basic/protected
  body: none
  auth: basic
}

auth:bearer {
   token: {{bearerAuthPassword}}
}

auth:basic {
  username: bruno
  password: {{basicAuthPassword}}
}
```

> (principle of least surprise)

This behaviour can be improved, but probably we should keep this ticket for a longer time and get more feedback before making any changes.

**Comment by lared** [comment]
Aaah now I see, it is actually pretty clever. I failed to notice that there is an Auth method selector in the method block.  Sorry for confusion!
