### ISSUE TITLE
[User Experience] When opening more requests that can fit into the tab bar, the currently opened request tab should always be visible

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#363]
It makes it a tad bit less confusing when navigating:

![](https://imgur.com/fuIiugi.png)

**Comment by therealrinku** [comment]
hey @helloanoop !

is someone working on this already ?

if not, I actually implemented a fix on the dev environment using unshift instead of push on the addTab function so that newly opened tab gets added to the first instead of last, 

and on the focusTab function, I removed the focused tab from the tabs and added it to the first using unshift as well,
and it all seems to be working well.

Let me know what do you think.

**Comment by anusree-bruno** [comment]
This issue has been fixed closing this.
