### ISSUE TITLE
Javascript API Down

### ISSUE THREAD

**Issue by andrew-telus** [usebruno/bruno#3639]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

https://docs.usebruno.com/scripting/javascript-reference

This page is down. Trying to figure out how global environment variables are supposed to work.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/2c86109f-9074-404c-abff-f5053c018c02)

**Comment by sanjai0py** [comment]
Hey @andrew-telus the updated route is https://docs.usebruno.com/testing/script/javascript-reference

**Comment by ganesh-bruno** [comment]
Hi @andrew-telus,

Thank you for reporting this issue.

We recently updated the documentation, combining the **Scripting and API Testing** sections into a unified **Tests and Script** section. If you encounter any navigation difficulties or notice any missing information, please don't hesitate to reach out.

Since the issue has already been addressed, I’m closing this for now.
