### ISSUE TITLE
[Feature request] allow export to Postman Collection

### ISSUE THREAD

**Issue by pove** [usebruno/bruno#401]
Right now it is possible to export collections in a "Bruno Collection" format. This json file cannot be imported into Postman. 
Can we allow export to both formats "Bruno Collection" and "Postman Collection"? It could help migration from Postman to Bruno on big teams when not everybody switch to Bruno from the beginning.

Discussion: #375

**Comment by ssnyder** [comment]
I too would love to be able to export to Postman or some other common format.   This would allow me to share more easily with folks that are not using Bruno.

**Comment by pove** [comment]
I am thinking... pre&post-scripts, assertions and test-scripts are compatible things to export?

**Comment by kapami** [comment]
Hello. 
I would love to work on this issue. Can you assign it to me please?

**Comment by helloanoop** [comment]
Hey @kapami 

Currently we don't have a process to assign it and then follow up.

You are free to pick any ticket.
You can comment that you are taking a stab at it, so that the community knows that you are working it.

As you make progress, keep sharing the progress in the ticket.

Raise a PR once ready.

**Comment by kapami** [comment]
Thank you for that information :) 

Then I will take a try and work on this issue.
