### ISSUE TITLE
Inbuilt Git Integration to sync requests from UI

### ISSUE THREAD

**Issue by n1rjal** [usebruno/bruno#461]
I see bruno has a huge capacity and I know my working team is ready to adopt it. But we have some interns/junior devs who is not self suffficeint with git and if there were a button that will sync, init and push the changes to a github repository from User interface like how vs studio has in their UI. I think it will be a game changer. We are currently using postman and we will love to switch it. I am even open t contributing to the feature myself.

**Comment by helloanoop** [comment]
Hey @n1rjal !

Glad that you like Bruno!

There are some things that we intend to provide in the Supported Edition. Inbuilt Git Integration is [one of them](https://github.com/usebruno/bruno/discussions/269#discussioncomment-7181580)

Just so that this don't set you alarm bells off,
95% of our features will always be freely available, with the code open sourced under the MIT license. We're committed to continuously developing both [core and advanced features](https://github.com/usebruno/bruno/discussions/384) for the benefit of all users. 

You can can read more about [long term vision](https://github.com/usebruno/bruno/discussions/269) and about the features that are planned [Supporter edition](https://github.com/usebruno/bruno/discussions/269#discussioncomment-7221852)

**Comment by krummbar** [comment]
@helloanoop @sanjai0py 
I think since the golden edition is available now, this issue can bei closed

**Comment by sanjai0py** [comment]
Closing this!

This feature has been implemented in the Golden Edition of Bruno!
