### ISSUE TITLE
Middle click on tab to close the tab

### ISSUE THREAD

**Issue by kpau** [usebruno/bruno#485]
Hello, the Bruno app is really great. Thanks!

I have one small request: Can you add support for closing the tab with mouse middle click?

**Comment by Thanush19** [comment]
can u describe the issue with some more more clearence, like send adequete screenchots of the issue @kpau ....

**Comment by kpau** [comment]
Currently we can close the tabs in the GUI client with the "X" button or with CTRL+W.
It would be useful if we could close the tabs when clicking them with the middle button of the mouse. The same way we can close the tabs in a web browser or VS Code.

![image](https://github.com/usebruno/bruno/assets/1583751/a86484b6-76c0-4690-b048-6fe67b1fff6b)

**Comment by tibormichel1** [comment]
Hello can i work on this issue ?

**Comment by tibormichel1** [comment]
Hello can i work on this issue ?

**Comment by Sahilm416** [comment]
@kpau will you please explain where the middle click event should happen , anywhere in main content section or just by pressing " X " on the tab ??

**Comment by jakoss** [comment]
Anywhere on the tab, it's pretty much default for any tab application these days

**Comment by kpau** [comment]
As @jakoss said, the tab should be closed by clicking anywhere on it with the middle button.
You should be able to close any tab in that way, not only the active one.
This behavior can be seen in any web browser and in VS code (probably most other apps with tabs too).
Thanks for working on it 🙂

**Comment by ravermeister** [comment]
Any news on this? Isn't it a quick win?

**Comment by shivamlikhar29** [comment]
Is this issue fixed ?

**Comment by ravermeister** [comment]
No

**Comment by Oxymoron290** [comment]
This conversation has seen various inputs and attempts at clarification, but it seems we've yet to converge on a solution that has been merged into the main codebase.

The request is to enable users to close tabs within the Bruno app by clicking anywhere on the tab with the middle mouse button, mirroring the functionality found in most web browsers and applications with tabbed interfaces, such as Visual Studio Code. This feature is not just a convenience but has become an expected behavior for users interacting with tabbed interfaces.

The middle mouse button's use for closing tabs has evolved into an emergent convention, as noted by Jeff Atwood in his [March 2008 blog post](https://blog.codinghorror.com/what-should-the-middle-mouse-button-mean/), highlighting its adoption in tabbed user interfaces. While acknowledging that there isn't a universal standard, the consistency in user experience across major platforms and applications suggests a strong user expectation for this behavior.

This feature's implementation would align Bruno with these user expectations, enhancing usability and the overall user experience. It's evident from the initial conversation and subsequent discussions that there is a user demand for this functionality, and it represents an opportunity to align with best practices in software design.

Given the history of this request and the community's support, I kindly urge the team to prioritize the review and merge of one of the existing pull requests that implement this feature or to provide guidance on what is needed for a pull request to be acceptable. This would not only fulfill a user request but also enhance the Bruno app's alignment with established conventions in user interface design.

I appreciate the team's hard work and dedication to improving the Bruno app. Implementing this feature would be a significant step forward in making the app even more user-friendly and intuitive.
