### ISSUE TITLE
Request named limited to 50 chars when renaming not creating 

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#501]
Created a request with a name length= 55 chars, and it cannot be renamed as long as the new name is more than 50 chars long.

To reproduce:
- create a request and named it with more than 50 chars
- double click (to rename)
- directly 9n Rename button

You will have an error message: `must be 50 characters or less`

**Comment by Its-treason** [comment]
This should be addressed with #349 length limit will be set 250 characters in this PR.

**Comment by waltribeiro** [comment]
Any update on this limitation for "must be 50 characters or less" ?

I ask because I'd like each of my API commands to have pretty slugs next to them.

For example:

`get -projects--id-devices | Retrieve All Devices Of A Project`

Rather than just `get -projects--id-devices`

<img width="1430" alt="Screenshot 2024-09-01 at 10 23 04 AM" src="https://github.com/user-attachments/assets/1b3c79f7-6d4a-4913-9b71-fd789398d4f3">

**Comment by helloanoop** [comment]
Just fixed this - https://github.com/usebruno/bruno/commit/eb6944a1c95a82566cf9d5be9d9bc0bce5273d37
This will be available in the next outgoing release of Bruno.
