### ISSUE TITLE
Export Open API 3.x Spec from Bruno

### ISSUE THREAD

**Issue by haveachin** [usebruno/bruno#502]

**Comment by game5413** [comment]
Hello, currently i'm developing this feature because it will help for anyone include myself to create API documentation. Right now i've got some progress for generating the collection, here some preview about what i'm working on.

https://github.com/usebruno/bruno/assets/37659721/d6ba9fcb-ccdd-44fa-a939-acded0f6b745

**Comment by helloanoop** [comment]
Closing this issue as this now supported in Bruno.
