### ISSUE TITLE
[Feature Request] Influence the Collection run order

### ISSUE THREAD

**Issue by mjhcorporate** [usebruno/bruno#534]
It would be great to have something like

```js
// set request by id
bru.setNextRequest(12)
// alternative: set request by name?
bru.setNextRequest("GET BookingDetails")
```

That way, we could do branches and loops for error-handling and async workflows.

**Comment by mjhcorporate** [comment]
Poking around the code:
- the CLI currently runs the collection in a straight order: https://github.com/usebruno/bruno/blob/6b668aaebeeb03fcaad0f17995c6f04af55ec9df/packages/bruno-cli/src/commands/run.js#L360
- UI runs requests in straight order as well, using a different loop: https://github.com/usebruno/bruno/blob/6b668aaebeeb03fcaad0f17995c6f04af55ec9df/packages/bruno-electron/src/ipc/network/index.js#L590
- `bru` class is defined here: https://github.com/usebruno/bruno/blob/6b668aaebeeb03fcaad0f17995c6f04af55ec9df/packages/bruno-js/src/bru.js#L4

**Comment by Zegnat** [comment]
I too wanted to specify the order of running my requests in a collection, and found this existing issue. But the solution I thought would be necessary is the oposite of what is being proposed here. So I thought I would drop in 2¢.

I would have thought the solution was to define dependents to a specific request. E.g. if I want to make a request to an authenticated endpoint, I require the `token` collection variable to be set. If it is not set, I need to first run a request to fetch a token.

With `bru.setNextRequest()` I would have to put that in my authentication flow. But the authentication flow does not actually know which one of my other requests I want to be running now. So what would fit here is a pre request script like (pseudocode):

```javascript
if (!bru.getVar("token")) {
    bru.doRequest("Get token");
}
```

**Comment by mj-h** [comment]
It seems you are coming from Insomnia 😂!  This automatic request-chaining is exactly the flow that they are using. It works well for explorative testing! I don't know how well it works for collection-runners, because Insomnia does not have a concept of collection runners.

Using `.setNextRequest` is possible for this, by saving the name of the current request into some variable, and then the auth-request uses that name to jump back. It's an ugly hack, but I have used it in Postman before. This needs #987 to work.

However, since auth is such a bog-standard use-case, there should be (and probably will be?) a simple way to say "use OAuth Token Flow" or so for a request. Postman (and, I think, Insomnia) both support this.

**Comment by Zegnat** [comment]
I am actually a hurl user looking for a more graphical package to recommend for those who do not like the plain files 😉 In hurl I have just been using separate files and putting them together:

``` bash
cat login.hurl action.hurl | hurl
```

Maybe auth was a bad example, because most platforms will make specific ways of handling it. I am doing some infrastructure as code at the moment where I need to fetch different resources. Certain requests might require I first look up tenant IDs, others may need credentials. Right now I can do this with something like (hypothetical):

```
cat get-tenant.hurl start-process.hurl | hurl
cat get-tenant.hurl create-database.hurl get-database-credentials.hurl start-process.hurl | hurl
```

> Using `.setNextRequest` is possible for this, by saving the name of the current request into some variable, and then the auth-request uses that name to jump back.

I will have another look at that. I am not sure I can visualise how this would work right now. How would my hypothetical `get-database-credentials` request know to first run `create-database`? Would the get do a `.setNextRequest("create-database")`, then fail its own request, then have create, and then create needs to check `bru.getVar("nextUp")` and if it was set by the getter do a `.setNextRequest` to it?

I feel that having to have a failing request as part of the flow is a bit weird.

**Comment by mj-h** [comment]
In Postman, what I always _wished_ for, but never worked, was to have a prerequest-script in the `get-database-credentials` request that checks: "Do I have a database id? If not, jump to `create-database` _without_ executing the `get-database-credentials` request". Alas, this was never possible. To avoid the "failing request as part of the flow", I ended up stuffing this sort of logic into the _previous_ request. Less ugly, but still not nice.

In the open PR, I implemented `setNextRequest` with a behavior that is very similar to Postman, to ease migration to / from Postman. 

Nice method of using `cat <files> | hurl` for controlling the exeuction flow externally! Is the flow-order always known to you before executing the collection? If so, then something like

```
bru run "my-req-1.bru" "my-req-2.bru"
```

would probably the cleanest approach. Also,

```
bru run "my-collection-A.bru" "my-collection-C.bru"
```

should be supported. Both don't currently work, and I don't see any open issues for them. Would that solve your issue?

**Comment by Zegnat** [comment]
> Is the flow-order always known to you before executing the collection?

Yes. Or a better way to phrase it: the dependencies for the second request are known to me.

> Would `bru run "my-req-1.bru" "my-req-2.bru"` solve your issue?

I will need to think about the consequences there. My main reason for switching to Bruno from hurl is the GUI, so the only solution being back in the cli feels wrong 😅

> Both don't currently work, and I don't see any open issues for them.

The reason I use `cat` for the hurl command instead of feeding 2 separate files is that hurl will not share state between the files. So it will very much depend on how Bruno implements it. I will have a good think about it and can put some time aside to open an issue for further discussion.

**Comment by helloanoop** [comment]
@Zegnat We will support `bru.runRequest()` to support your usecase

```
if (!bru.getVar("token")) {
    bru.runRequest("Get token");
}
```

**Comment by helloanoop** [comment]
`bru.setNextRequest()` is live ! 🎊 

GUI - v1.4.0
CLI - v1.2.0

**Comment by Zegnat** [comment]
Amazing work @helloanoop @mj-h 👏 I’ll make some time to try it out this weekend!
