### ISSUE TITLE
Release 1.0.0 version

### ISSUE THREAD

**Issue by vlsi** [usebruno/bruno#643]
Hi, thanks for sharing bruno. Unfortunately, it is common for people to treat 0.x versions as "unstable", so they are inherently reluctant to using such "unstable" versions.

I believe bruno 0.25 is mature enough to be released as 1.0.0. WDYT? 

----
Updates from @helloanoop 
Release 1.0.0 planned to go live on `Sunday, Oct 29th 2023`

**Comment by Its-treason** [comment]
Hey @vlsi, we want to implement more feature and polish the App before releasing V1! Anoop made an extensive roadmap to V1 here: https://github.com/usebruno/bruno/discussions/384 to track the development process.

**Comment by vlsi** [comment]
I fully understand your intention, and I appreciate the roadmap.
However, what do you think of releasing one of the upcoming versions as 1.0.0, and implement "all your 1.0 plans in 2.0" instead?

I believe the current set of features qualifies for 1.0, and users would be equally happy to get "OAuth in Bruno 2.0".
As for me, releasing 1.0 today is a "cosmetic-only" change, however, I believe it is important for building the community, and 0.x versioning is indeed distracting many users.

Here's some context behind the ask: I just chatted on "let's convince someone to deliver a Bruno-related talk on a testing conference", and the other person said "oh, the tool does not have 1.0 yet so it is not mature enough".
I'm not pushing you here, however, it looks like you might be falling into "ah it is not ready for 1.0" trap while the tool might already be quite helpful for many users.

The story reminds me Terraform which was in 0.1..0.15 for many years, and they eventually renamed it to 1.0 with virtually no changes.

**Comment by premeaswaran** [comment]
I agree with @vlsi on his point. Though it is respectable that you try to stick to the roadmap and ship all planned features in 1.0, I would like the versioning not be a clincher to stop someone while trying to address the elephant in the room (based on the recent events).

May be if OAuth is almost done (I remember seeing on the issue that it should be ready to be live anytime sooner), I would love an 1.0 with what we have right now + OAuth.

Just sharing my opinion.

**Comment by helloanoop** [comment]
We are set to launch `v1.0.0` on October 29, 2023, with our stable feature set. 

While I would have preferred to complete the OAuth2 and cookies features before announcing V1, the time left is too short. I also need to prepare for my [IndiaFoss 3.0 Talk & Project Showcase](https://indiafoss.net/2023). Unfortunately, I fell sick during the recent 4-day holiday in India, which dashed hopes of getting these across the goal line.

**v1.0.0** is not about having all the features but rather a message that our current platform is stable and suitable for use in production settings by teams. Many teams find our existing Bruno version to be perfectly sufficient for their needs.

It took 2 years to advance from **0.1.0** to **0.12.0**
And 1 month to go from **0.12.0** to **0.27.0** (since the rise that began on Sep 28th 2023)

We've been releasing updates every alternate day for the past month.
This incredible pace of development would not have been possible without the dedication, love, and contributions from our vibrant community. We've received valuable code contributions, identified and addressed issues, and gathered essential feedback.

Looking forward to Sun Oct 29th 2023.

Best,
Anoop

**Comment by dw-0** [comment]
@helloanoop was that v1.0.0 release intentional? 😄 looks a bit weird that only a single new feature made it into v1 and it wasn't even one listed in the v1 milestone.

general question just out of curiosity: how will you further manage versioning? will you follow the semver scheme? what are the milestones actually suppose to mean for that project?

**Comment by dw-0** [comment]
Good point, didn't noticed that. And yeah, i understood the reason behind a near v1 release and i agree with it. I just wondered about THAT v1 release :)

**Comment by Zer0x00** [comment]
Can this issue be closed since v1.0.0 is now released?

There is also a pretty relevant PR that was waiting for the v1 release: https://github.com/usebruno/bruno/pull/493

**Comment by mohamedgomran** [comment]
@vlsi @helloanoop Can you please close this? it's resolved :)
