### ISSUE TITLE
[Bug] Comments in .env file cause requests to crash in Bruno CLI but not in Bruno application

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#701]
Comments defined with `#` in `.env` file are allowed and everything works fine in Bruno application but If I try to run requests in Bruno CLI it fails with the following error:

![image](https://github.com/usebruno/bruno/assets/1073299/d4a449a2-a189-4563-96a4-965d33c1f959)

`.env` file is defined like this:

```env
# COMMENT

ABC=xyz
CBA=zyx
```

Bru CLI: 0.14.0 on Windows

**Comment by helloanoop** [comment]
Just published `v0.15.0` on npm with the CLI getting all the latest upgrades from other monorepos.

@martinsefcik Can you confirm if this issue still exists?

**Comment by helloanoop** [comment]
Thanks @martinsefcik 

Just pushed the fix for this and released Bruno CLI `v0.15.1`

> Or in general wouldn't it be better to release bruno-cli always together with releasing bruno-app

Releasing `bruno-app` and `bruno-cli` together everytime might not be the best approach as sometimes there is no cli release needed in many cases. Bruno strictly doesn't follow a monorepo model (like lerna ..etc) that takes care of these things. Perhaps in the future we need to adopt workflows that handle these cases.

**Comment by martinsefcik** [comment]
@helloanoop Thanks, it was fast :)

I can confirm 0.15.1 is working and also comments in .env file are not a problem anymore. 
So this issue can be closed as resolved.

But I have another difference between app and cli with axios requests (in pre request script) which does not behave the same way, but I will create separate ticket for that.

**Comment by helloanoop** [comment]
Awesome. Thanks @martinsefcik !

**Comment by martinsefcik** [comment]
@helloanoop here is the second issue (app vs. cli) I mentioned here in before #759
