### ISSUE TITLE
[Feature Request] Option when click on the request tab

### ISSUE THREAD

**Issue by smdedar** [usebruno/bruno#715]
- User can close all tab / single tab
- User can duplicate a tab
- User can close all right / left tab
![image](https://github.com/usebruno/bruno/assets/30989286/7acb4706-f566-49ef-a0e5-1d3d92791c7f)

**Comment by lewisst** [comment]
Can i suggest enabling middle click to close tab?

**Comment by flof** [comment]
First of all, i like the suggestion for a tab context menu with 

- New request
- Close tab
- Close other tabs
- Close all tabs

I am not sure about

- Force close tab
- Force close all tabs

These bring much noise into the context menu in my opinion and force users to read a lot of text. And they introduce the danger of accidentally choose **Force close all** instead of **Close all**, which can lead to data loss.

Instead of "Force close all tabs", the dialog that appears for each request with unsaved changes could provide a checkbox "Apply for all" or something like that.

Regarding "Duplicate tab": This is an interesting one. What behavior do you have in mind here?

- A: Clone the request (like the clone command in the request list)
- B: Open the same request again in a new tab (lie Postman does)

**Comment by Phyziik** [comment]
closes #1105

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue has been resolved as per our latest release(1.34.2), Thanks!
