### ISSUE TITLE
Error creating New Collections

### ISSUE THREAD

**Issue by Pessiun** [usebruno/bruno#760]
![image](https://github.com/usebruno/bruno/assets/148357093/28e06eb8-9e51-4354-a685-6819bc2bf54e)

**Comment by Pessiun** [comment]
> Could you elaborate? What happens when you click create? :)

When I click on Create
Results an Error with message, "an error occurred while creating the collection"
Expected results a collection should be created

**Comment by nlynzaad** [comment]
Just some feedback from my own experience. 

Had the same error popup. Turns out it was due to a "&" character in my path. When ever the filepath contained a "&" character in the path name the error would occur. 

Generates Error
![image](https://github.com/usebruno/bruno/assets/44094871/3354d97f-8830-4aea-8449-594603d2b3b8)

Successfully creates collection:

![image](https://github.com/usebruno/bruno/assets/44094871/6ed3ecc2-6243-4480-a874-308d7a852e3b)

**Comment by em3link** [comment]
I installed Bruno with Flatpak and had the same issue on Pop!_OS.
The solution for me was to give permission to the app to access the filesystem (using Flatseal, but you can also use the command line for that).
The Bruno app should probably request access to the filesystem by default, but well at least it seems to work now.

**Comment by sanjai0py** [comment]
I have marked this issue as closed since it appears to have been resolved by the author. Please open a new issue if it still persists!
