### ISSUE TITLE
Can't create environment variable with a "-" in the name

### ISSUE THREAD

**Issue by ljohnston** [usebruno/bruno#853]
I have environments with variable names like `some-service-url`. This has worked in the past. I just upgraded to 1.0.1 and it seems that dashes are not allowed in variable names. Is this intentional or is this a bug?

<img width="350" alt="image" src="https://github.com/usebruno/bruno/assets/361524/f67d1ff6-23c7-407e-80d8-19153bc9dcc5">

Note that this creates issues when importing a Postman collection (where variable names with dashes _are_ allowed). After importing a Postman collection that has requests defined as `GET {{some-service-url}}/api/v1/...`, for example, you can't create an environment variable in Bruno that will allow that request to be sent. To get things to work, you'd first have to modify every request imported from the collection to remove the dashes.

**Comment by n00o** [comment]
I think this intended and was added on merge request #791. This is something that I also noticed because I have to pass a header that uses "-" for authorization and couldn't because both headers and environment variables can't have that character.

I would think the regex statement used for validation should be `^(?!\d)[\w-]*$` instead of `^(?!\d)\w*$`. Although there could be other characters that Postman and others allows that we should add for compatibility reasons.

**Comment by helloanoop** [comment]
@ljohnston We will add support back or `-`. See https://github.com/usebruno/bruno/issues/682#issuecomment-1790236386

> To get things to work, you'd first have to modify every request imported from the collection to remove the dashes.

Will release a patch fix soon, meanwhile as a temporary workaround - you can open the collection folder in vscode/any editor and do a find and replace 

![image](https://github.com/usebruno/bruno/assets/9350733/f880feb0-e257-4187-9de2-0e4ad7e5bc88)
