### ISSUE TITLE
[Feature Request] Better javascript editor for tests and scripts

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [usebruno/bruno#861]
Right now it is very hard to find javascript syntax errors in the test and scripts section, especially when it get's complicated.

It would be awesome to have two things:

1. syntax error check and error highlighting. Example, this should mark an error in line 1: 
```js
if (p {
 var om = 'ah';    
}
```
2. code completion suggestions, like in the developer console. for example if one types `bru.` , setVar, getVar, etc should be suggested and selectable.

That would be fantastic!

**Comment by n00o** [comment]
I agree, this would be a great feature. Probably the best way to implement it we would be use autocompletion in CodeMirror. Here is an example of it: https://codemirror.net/examples/autocompletion/. It should be possible to add all the `bru` functions to the script tabs as well. 

Currently it seems that Bruno is using the same type of CodeMirror component in the pre/post script as it does for the response and body which is not not ideal. It might be good to consider making a separate CodeMirrorScript component that has all the autocompletion options included as including it in the response and body is pretty pointless.

I will try to take a look at this since I have already done some other stuff with CodeMirror.
